/* Generated by re2c 0.14.3 */
// Copyright 2011 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "lexer.h"

#include <stdio.h>

#include "eval_env.h"
#include "graph.h"
#include "util.h"

size_t AdvanceToNextManifestChunk(StringPiece content, size_t idx) {
  assert(idx <= content.size());

  // Iterate over each LF in the manifest, starting at the given index.
  while (true) {
    const void* next_line = memchr(content.data() + idx, '\n',
                                   content.size() - idx);
    if (next_line == nullptr) {
      break;
    }
    idx = static_cast<const char*>(next_line) - content.data();
    ++idx; // step over the LF

    // The line must not be preceded by a line continuator. This logic can
    // filter out more split candidates than strictly necessary:
    //  - The preceding line could have a comment that ends with a "$": "# $\n"
    //  - The preceding line could end with an escaped-dollar: "X=$$\n"
    if ((idx >= 2 && content.substr(idx - 2, 2) == "$\n") ||
        (idx >= 3 && content.substr(idx - 3, 3) == "$\r\n")) {
      continue;
    }

    // Skip an indented line or a comment line, either of which could be part of
    // an earlier declaration. Ninja allows unindented comments (as well as
    // indented comments) inside a binding block, e.g.:
    //
    //   build foo: cc
    //   # comment-line
    //     pool = link_pool
    //
    // Ninja doesn't allow blank lines in a binding block. This code could
    // probably allow a chunk to start with a blank line, but it seems better if
    // it doesn't.
    if (idx >= content.size() ||
        content[idx] == ' ' || content[idx] == '#' ||
        content[idx] == '\r' || content[idx] == '\n') {
      continue;
    }

    return idx;
  }

  return content.size();
}

bool DecorateErrorWithLocation(const std::string& filename,
                               const char* file_start,
                               size_t file_offset,
                               const std::string& message,
                               std::string* err) {
  // Make a copy in case message and err alias.
  std::string message_tmp = message;

  // Compute line/column.
  int line = 1;
  const char* line_start = file_start;
  const char* file_pos = file_start + file_offset;

  for (const char* p = line_start; p < file_pos; ++p) {
    if (*p == '\n') {
      ++line;
      line_start = p + 1;
    }
  }
  int col = (int)(file_pos - line_start);

  char buf[1024];
  snprintf(buf, sizeof(buf), "%s:%d: ", filename.c_str(), line);
  *err = buf;
  *err += message_tmp + "\n";

  // Add some context to the message.
  const int kTruncateColumn = 72;
  if (col > 0 && col < kTruncateColumn) {
    int len;
    bool truncated = true;
    for (len = 0; len < kTruncateColumn; ++len) {
      if (line_start[len] == 0 || line_start[len] == '\n') {
        truncated = false;
        break;
      }
    }
    *err += string(line_start, len);
    if (truncated)
      *err += "...";
    *err += "\n";
    *err += string(col, ' ');
    *err += "^ near here";
  }

  return false;
}

bool Lexer::Error(const std::string& message, std::string* err) {
  return DecorateErrorWithLocation(filename_, input_.data(),
                                   GetLastTokenOffset(), message, err);
}

bool Lexer::UnexpectedNulError(const char* pos, std::string* err) {
  assert(*pos == '\0');
  const char* msg = (pos == EndOfFile()) ? "unexpected EOF"
                                         : "unexpected NUL byte";
  return Error(msg, err);
}

const char* Lexer::TokenName(Token t) {
  switch (t) {
  case ERROR:    return "lexing error";
  case BUILD:    return "'build'";
  case COLON:    return "':'";
  case DEFAULT:  return "'default'";
  case EQUALS:   return "'='";
  case IDENT:    return "identifier";
  case INCLUDE:  return "'include'";
  case INDENT:   return "indent";
  case NEWLINE:  return "newline";
  case PIPE2:    return "'||'";
  case PIPE:     return "'|'";
  case PIPEAT:   return "'|@'";
  case POOL:     return "'pool'";
  case RULE:     return "'rule'";
  case SUBNINJA: return "'subninja'";
  case TNUL:     return "nul byte";
  case TEOF:     return "eof";
  }
  return NULL;  // not reached
}

const char* Lexer::TokenErrorHint(Token expected) {
  switch (expected) {
  case COLON:
    return " ($ also escapes ':')";
  default:
    return "";
  }
}

string Lexer::DescribeLastError() {
  if (last_token_) {
    switch (last_token_[0]) {
    case '\t':
      return "tabs are not allowed, use spaces";
    }
  }
  return "lexing error";
}

void Lexer::UnreadToken() {
  ofs_ = last_token_;
}

Lexer::Token Lexer::ReadToken() {
  const char* p = ofs_;
  const char* q;
  const char* r;
  const char* start;
  Lexer::Token token;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,   0,  64,  64,   0,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		192,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  96,  96,  64, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  64,  64,  64,  64,  64,  64, 
		 64,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  64,  64,  64,  64,  96, 
		 64,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
	};

	yych = *p;
	if (yych <= 'Z') {
		if (yych <= '#') {
			if (yych <= '\f') {
				if (yych <= 0x00) goto yy23;
				if (yych == '\n') goto yy6;
				goto yy25;
			} else {
				if (yych <= 0x1F) {
					if (yych <= '\r') goto yy8;
					goto yy25;
				} else {
					if (yych <= ' ') goto yy2;
					if (yych <= '"') goto yy25;
					goto yy4;
				}
			}
		} else {
			if (yych <= '9') {
				if (yych <= ',') goto yy25;
				if (yych == '/') goto yy25;
				goto yy22;
			} else {
				if (yych <= '<') {
					if (yych <= ':') goto yy16;
					goto yy25;
				} else {
					if (yych <= '=') goto yy14;
					if (yych <= '@') goto yy25;
					goto yy22;
				}
			}
		}
	} else {
		if (yych <= 'i') {
			if (yych <= 'a') {
				if (yych == '_') goto yy22;
				if (yych <= '`') goto yy25;
				goto yy22;
			} else {
				if (yych <= 'c') {
					if (yych <= 'b') goto yy9;
					goto yy22;
				} else {
					if (yych <= 'd') goto yy13;
					if (yych <= 'h') goto yy22;
					goto yy20;
				}
			}
		} else {
			if (yych <= 'r') {
				if (yych == 'p') goto yy11;
				if (yych <= 'q') goto yy22;
				goto yy12;
			} else {
				if (yych <= 'z') {
					if (yych <= 's') goto yy21;
					goto yy22;
				} else {
					if (yych == '|') goto yy18;
					goto yy25;
				}
			}
		}
	}
yy2:
	yyaccept = 0;
	yych = *(q = ++p);
	goto yy75;
yy3:
	{ token = INDENT;   break; }
yy4:
	r = p + 1;
	yyaccept = 1;
	yych = *(q = ++p);
	if (yych >= 0x01) goto yy69;
yy5:
	{ token = ERROR;    break; }
yy6:
	++p;
yy7:
	{ token = NEWLINE;  break; }
yy8:
	yych = *++p;
	if (yych == '\n') goto yy67;
	goto yy5;
yy9:
	++p;
	if ((yych = *p) == 'u') goto yy62;
	goto yy27;
yy10:
	{ token = IDENT;    break; }
yy11:
	yych = *++p;
	if (yych == 'o') goto yy58;
	goto yy27;
yy12:
	yych = *++p;
	if (yych == 'u') goto yy54;
	goto yy27;
yy13:
	yych = *++p;
	if (yych == 'e') goto yy47;
	goto yy27;
yy14:
	++p;
	{ token = EQUALS;   break; }
yy16:
	++p;
	{ token = COLON;    break; }
yy18:
	++p;
	if ((yych = *p) == '@') goto yy45;
	if (yych == '|') goto yy43;
	{ token = PIPE;     break; }
yy20:
	yych = *++p;
	if (yych == 'n') goto yy36;
	goto yy27;
yy21:
	yych = *++p;
	if (yych == 'u') goto yy28;
	goto yy27;
yy22:
	yych = *++p;
	goto yy27;
yy23:
	++p;
	{ token = (start == EndOfFile()) ? TEOF : TNUL; break; }
yy25:
	yych = *++p;
	goto yy5;
yy26:
	++p;
	yych = *p;
yy27:
	if (yybm[0+yych] & 32) {
		goto yy26;
	}
	goto yy10;
yy28:
	yych = *++p;
	if (yych != 'b') goto yy27;
	yych = *++p;
	if (yych != 'n') goto yy27;
	yych = *++p;
	if (yych != 'i') goto yy27;
	yych = *++p;
	if (yych != 'n') goto yy27;
	yych = *++p;
	if (yych != 'j') goto yy27;
	yych = *++p;
	if (yych != 'a') goto yy27;
	++p;
	if (yybm[0+(yych = *p)] & 32) {
		goto yy26;
	}
	{ token = SUBNINJA; break; }
yy36:
	yych = *++p;
	if (yych != 'c') goto yy27;
	yych = *++p;
	if (yych != 'l') goto yy27;
	yych = *++p;
	if (yych != 'u') goto yy27;
	yych = *++p;
	if (yych != 'd') goto yy27;
	yych = *++p;
	if (yych != 'e') goto yy27;
	++p;
	if (yybm[0+(yych = *p)] & 32) {
		goto yy26;
	}
	{ token = INCLUDE;  break; }
yy43:
	++p;
	{ token = PIPE2;    break; }
yy45:
	++p;
	{ token = PIPEAT;   break; }
yy47:
	yych = *++p;
	if (yych != 'f') goto yy27;
	yych = *++p;
	if (yych != 'a') goto yy27;
	yych = *++p;
	if (yych != 'u') goto yy27;
	yych = *++p;
	if (yych != 'l') goto yy27;
	yych = *++p;
	if (yych != 't') goto yy27;
	++p;
	if (yybm[0+(yych = *p)] & 32) {
		goto yy26;
	}
	{ token = DEFAULT;  break; }
yy54:
	yych = *++p;
	if (yych != 'l') goto yy27;
	yych = *++p;
	if (yych != 'e') goto yy27;
	++p;
	if (yybm[0+(yych = *p)] & 32) {
		goto yy26;
	}
	{ token = RULE;     break; }
yy58:
	yych = *++p;
	if (yych != 'o') goto yy27;
	yych = *++p;
	if (yych != 'l') goto yy27;
	++p;
	if (yybm[0+(yych = *p)] & 32) {
		goto yy26;
	}
	{ token = POOL;     break; }
yy62:
	yych = *++p;
	if (yych != 'i') goto yy27;
	yych = *++p;
	if (yych != 'l') goto yy27;
	yych = *++p;
	if (yych != 'd') goto yy27;
	++p;
	if (yybm[0+(yych = *p)] & 32) {
		goto yy26;
	}
	{ token = BUILD;    break; }
yy67:
	yych = *++p;
	goto yy7;
yy68:
	r = p + 1;
	++p;
	yych = *p;
yy69:
	if (yybm[0+yych] & 64) {
		goto yy68;
	}
	if (yych <= 0x00) goto yy70;
	if (yych <= '\n') goto yy71;
	goto yy73;
yy70:
	p = q;
	if (yyaccept == 0) {
		goto yy3;
	} else {
		goto yy5;
	}
yy71:
	++p;
	p = r;
	{ continue; }
yy73:
	yych = *++p;
	if (yych == '\n') goto yy71;
	goto yy70;
yy74:
	yyaccept = 0;
	q = ++p;
	yych = *p;
yy75:
	if (yybm[0+yych] & 128) {
		goto yy74;
	}
	if (yych <= '\f') {
		if (yych == '\n') goto yy67;
		goto yy3;
	} else {
		if (yych <= '\r') goto yy76;
		if (yych == '#') goto yy68;
		goto yy3;
	}
yy76:
	++p;
	if ((yych = *p) == '\n') goto yy67;
	goto yy70;
}

  }

  last_token_ = start;
  ofs_ = p;
  if (token != NEWLINE && token != TEOF)
    EatWhitespace();
  return token;
}

bool Lexer::PeekIndent() {
  const char* p = ofs_;
  const char* q;
  const char* start;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,   0,  64,  64,   0,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		192,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
	};
	yych = *p;
	if (yych <= '\r') {
		if (yych == '\n') goto yy83;
		if (yych <= '\f') goto yy86;
		goto yy85;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy86;
		} else {
			if (yych == '#') goto yy81;
			goto yy86;
		}
	}
	yyaccept = 0;
	yych = *(q = ++p);
	goto yy95;
yy80:
	{ last_token_ = start; ofs_ = p; return true; }
yy81:
	yyaccept = 1;
	yych = *(q = ++p);
	if (yych >= 0x01) goto yy89;
yy82:
	{ last_token_ = ofs_ = start; return false; }
yy83:
	++p;
yy84:
	{ last_token_ = ofs_ = start; return false; }
yy85:
	yych = *++p;
	if (yych == '\n') goto yy87;
	goto yy82;
yy86:
	yych = *++p;
	goto yy82;
yy87:
	yych = *++p;
	goto yy84;
yy88:
	++p;
	yych = *p;
yy89:
	if (yybm[0+yych] & 64) {
		goto yy88;
	}
	if (yych <= 0x00) goto yy90;
	if (yych <= '\n') goto yy91;
	goto yy93;
yy90:
	p = q;
	if (yyaccept == 0) {
		goto yy80;
	} else {
		goto yy82;
	}
yy91:
	++p;
	{ continue; }
yy93:
	yych = *++p;
	if (yych == '\n') goto yy91;
	goto yy90;
yy94:
	yyaccept = 0;
	q = ++p;
	yych = *p;
yy95:
	if (yybm[0+yych] & 128) {
		goto yy94;
	}
	if (yych <= '\f') {
		if (yych == '\n') goto yy87;
		goto yy80;
	} else {
		if (yych <= '\r') goto yy96;
		if (yych == '#') goto yy88;
		goto yy80;
	}
yy96:
	++p;
	if ((yych = *p) == '\n') goto yy87;
	goto yy90;
}

  }
}

bool Lexer::PeekToken(Token token) {
  Token t = ReadToken();
  if (t == token)
    return true;
  UnreadToken();
  return false;
}

void Lexer::EatWhitespace() {
  const char* p = ofs_;
  const char* q;
  for (;;) {
    ofs_ = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *p;
	if (yych <= ' ') {
		if (yych <= 0x00) goto yy103;
		if (yych <= 0x1F) goto yy105;
	} else {
		if (yych == '$') goto yy101;
		goto yy105;
	}
	++p;
	yych = *p;
	goto yy111;
yy100:
	{ continue; }
yy101:
	yych = *(q = ++p);
	if (yych == '\n') goto yy106;
	if (yych == '\r') goto yy108;
yy102:
	{ break; }
yy103:
	++p;
	{ break; }
yy105:
	yych = *++p;
	goto yy102;
yy106:
	++p;
	{ continue; }
yy108:
	yych = *++p;
	if (yych == '\n') goto yy106;
	p = q;
	goto yy102;
yy110:
	++p;
	yych = *p;
yy111:
	if (yybm[0+yych] & 128) {
		goto yy110;
	}
	goto yy100;
}

  }
}

bool Lexer::ReadIdent(StringPiece* out) {
  const char* p = ofs_;
  const char* start;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0, 128, 128,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *p;
	if (yych <= '@') {
		if (yych <= '.') {
			if (yych <= ',') goto yy116;
		} else {
			if (yych <= '/') goto yy116;
			if (yych >= ':') goto yy116;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy114;
			if (yych <= '^') goto yy116;
		} else {
			if (yych <= '`') goto yy116;
			if (yych >= '{') goto yy116;
		}
	}
yy114:
	++p;
	yych = *p;
	goto yy119;
yy115:
	{
      *out = StringPiece(start, p - start);
      break;
    }
yy116:
	++p;
	{
      last_token_ = start;
      return false;
    }
yy118:
	++p;
	yych = *p;
yy119:
	if (yybm[0+yych] & 128) {
		goto yy118;
	}
	goto yy115;
}

  }
  last_token_ = start;
  ofs_ = p;
  EatWhitespace();
  return true;
}

bool Lexer::ReadBindingValue(StringPiece* out, string* err) {
  const char* p = ofs_;
  const char* q;
  const char* start;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,   0,  32,  32,   0,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,   0,  32,  32,  32, 
		 32,  32,  32,  32,  32, 224, 160,  32, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224,  32,  32,  32,  32,  32,  32, 
		 32, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224,  32,  32,  32,  32, 224, 
		 32, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
	};
	yych = *p;
	if (yych <= '\f') {
		if (yych <= 0x00) goto yy129;
		if (yych == '\n') goto yy126;
	} else {
		if (yych <= '\r') goto yy128;
		if (yych == '$') goto yy124;
	}
	yyaccept = 0;
	yych = *(q = ++p);
	goto yy139;
yy123:
	{
      continue;
    }
yy124:
	++p;
	if ((yych = *p) <= '-') {
		if (yych <= 0x1F) {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy132;
				goto yy138;
			} else {
				if (yych == '\r') goto yy134;
				goto yy132;
			}
		} else {
			if (yych <= '#') {
				if (yych <= ' ') goto yy135;
				goto yy132;
			} else {
				if (yych <= '$') goto yy135;
				if (yych <= ',') goto yy132;
				goto yy136;
			}
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '9') {
				if (yych <= '/') goto yy132;
				goto yy136;
			} else {
				if (yych <= ':') goto yy135;
				if (yych <= '@') goto yy132;
				goto yy136;
			}
		} else {
			if (yych <= '`') {
				if (yych == '_') goto yy136;
				goto yy132;
			} else {
				if (yych <= 'z') goto yy136;
				if (yych <= '{') goto yy137;
				goto yy132;
			}
		}
	}
yy125:
	{
      last_token_ = start;
      return Error(DescribeLastError(), err);
    }
yy126:
	++p;
yy127:
	{
      break;
    }
yy128:
	yych = *++p;
	if (yych == '\n') goto yy131;
	goto yy125;
yy129:
	++p;
	{
      last_token_ = start;
      return UnexpectedNulError(start, err);
    }
yy131:
	yych = *++p;
	goto yy127;
yy132:
	++p;
yy133:
	{
      last_token_ = start;
      return Error("bad $-escape (literal $ must be written as $$)", err);
    }
yy134:
	yych = *++p;
	if (yych == '\n') goto yy138;
	goto yy133;
yy135:
	yyaccept = 0;
	yych = *(q = ++p);
	goto yy139;
yy136:
	yyaccept = 0;
	yych = *(q = ++p);
	if (yybm[0+yych] & 64) {
		goto yy142;
	}
	goto yy139;
yy137:
	yyaccept = 1;
	yych = *(q = ++p);
	if (yybm[0+yych] & 128) {
		goto yy146;
	}
	goto yy133;
yy138:
	yyaccept = 0;
	q = ++p;
	yych = *p;
yy139:
	if (yybm[0+yych] & 32) {
		goto yy138;
	}
	if (yych <= '\r') goto yy123;
yy140:
	++p;
	yych = *p;
	if (yybm[0+yych] & 64) {
		goto yy142;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy138;
		} else {
			if (yych <= '\r') goto yy145;
			if (yych >= ' ') goto yy138;
		}
	} else {
		if (yych <= '/') {
			if (yych == '$') goto yy138;
		} else {
			if (yych <= ':') goto yy138;
			if (yych <= '`') goto yy141;
			if (yych <= '{') goto yy144;
		}
	}
yy141:
	p = q;
	if (yyaccept == 0) {
		goto yy123;
	} else {
		goto yy133;
	}
yy142:
	yyaccept = 0;
	q = ++p;
	yych = *p;
	if (yybm[0+yych] & 64) {
		goto yy142;
	}
	if (yych <= '\f') {
		if (yych <= 0x00) goto yy123;
		if (yych == '\n') goto yy123;
		goto yy138;
	} else {
		if (yych <= '\r') goto yy123;
		if (yych == '$') goto yy140;
		goto yy138;
	}
yy144:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy146;
	}
	goto yy141;
yy145:
	++p;
	yych = *p;
	if (yych == '\n') goto yy138;
	goto yy141;
yy146:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy146;
	}
	if (yych == '}') goto yy138;
	goto yy141;
}

  }
  *out = StringPiece(ofs_, p - ofs_);
  last_token_ = start;
  ofs_ = p;
  // Non-path strings end in newlines, so there's no whitespace to eat.
  return true;
}

StringPiece Lexer::PeekCanonicalPath() {
  auto finish = [this](const char* start, const char* end) {
    ofs_ = end;
    EatWhitespace();
    return StringPiece(start, end - start);
  };

  const char* p = ofs_;
  const char* q;
  const char* r;
  last_token_ = ofs_;

  do {
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128,   0, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		  0, 128, 128, 128,   0, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128,   0, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy154;
			if (yych == '\n') goto yy154;
			goto yy153;
		} else {
			if (yych <= '\r') goto yy154;
			if (yych == ' ') goto yy154;
			goto yy153;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy154;
			if (yych <= '-') goto yy153;
			if (yych <= '.') goto yy152;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy153;
				goto yy154;
			} else {
				if (yych == '|') goto yy154;
				goto yy153;
			}
		}
	}
	yych = *(q = ++p);
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy151;
			if (yych != '\n') goto yy155;
		} else {
			if (yych <= '\r') goto yy151;
			if (yych != ' ') goto yy155;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy151;
			if (yych <= '-') goto yy155;
			if (yych <= '.') goto yy182;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy155;
			} else {
				if (yych != '|') goto yy155;
			}
		}
	}
yy151:
	{ break;                      }
yy152:
	yych = *(q = ++p);
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy151;
			if (yych == '\n') goto yy151;
			goto yy155;
		} else {
			if (yych <= '\r') goto yy151;
			if (yych == ' ') goto yy151;
			goto yy155;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy151;
			if (yych <= '-') goto yy155;
			if (yych <= '.') goto yy167;
			goto yy166;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy155;
				goto yy151;
			} else {
				if (yych == '|') goto yy151;
				goto yy155;
			}
		}
	}
yy153:
	r = p + 1;
	yych = *(q = ++p);
	if (yych <= 0x00) goto yy151;
	if (yych == '$') goto yy151;
	goto yy156;
yy154:
	yych = *++p;
	goto yy151;
yy155:
	r = p + 1;
	++p;
	yych = *p;
yy156:
	if (yybm[0+yych] & 128) {
		goto yy155;
	}
	if (yych <= '\r') {
		if (yych <= 0x00) goto yy157;
		if (yych <= '\n') goto yy159;
		goto yy161;
	} else {
		if (yych <= ' ') goto yy159;
		if (yych <= '$') goto yy157;
		if (yych <= '/') goto yy158;
		goto yy159;
	}
yy157:
	p = q;
	goto yy151;
yy158:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy162;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy162;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy162;
			if (yych <= '.') goto yy164;
			goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy162;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy162;
			}
		}
	}
yy159:
	++p;
	p = r;
	{ return finish(ofs_, p);     }
yy161:
	yych = *++p;
	if (yych == '\n') goto yy159;
	goto yy157;
yy162:
	r = p + 1;
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy159;
			goto yy162;
		} else {
			if (yych <= '\r') goto yy161;
			if (yych == ' ') goto yy159;
			goto yy162;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '$') goto yy157;
			if (yych == '/') goto yy158;
			goto yy162;
		} else {
			if (yych <= ':') goto yy159;
			if (yych == '|') goto yy159;
			goto yy162;
		}
	}
yy164:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy162;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy162;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy162;
			if (yych >= '/') goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy162;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy162;
			}
		}
	}
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy162;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy162;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '$') goto yy157;
			if (yych == '/') goto yy157;
			goto yy162;
		} else {
			if (yych <= ':') goto yy157;
			if (yych == '|') goto yy157;
			goto yy162;
		}
	}
yy166:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy171;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy171;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy171;
			if (yych <= '.') goto yy170;
			goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy171;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy171;
			}
		}
	}
yy167:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy155;
	}
	if (yych <= '$') goto yy157;
	if (yych >= '0') goto yy157;
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy155;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy155;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy155;
			if (yych >= '/') goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy155;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy155;
			}
		}
	}
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy155;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy155;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy155;
			if (yych <= '.') goto yy167;
			goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy155;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy155;
			}
		}
	}
yy170:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy171;
			if (yych <= '.') goto yy181;
			goto yy157;
		} else {
			if (yych <= ':') {
				if (yych >= ':') goto yy157;
			} else {
				if (yych == '|') goto yy157;
			}
		}
	}
yy171:
	r = p + 1;
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy174;
			goto yy171;
		} else {
			if (yych <= '\r') goto yy176;
			if (yych == ' ') goto yy174;
			goto yy171;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '$') goto yy157;
			if (yych != '/') goto yy171;
		} else {
			if (yych <= ':') goto yy174;
			if (yych == '|') goto yy174;
			goto yy171;
		}
	}
yy173:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy177;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy177;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy177;
			if (yych <= '.') goto yy179;
			goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy177;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy177;
			}
		}
	}
yy174:
	++p;
	p = r;
	{ return finish(ofs_ + 2, p); }
yy176:
	yych = *++p;
	if (yych == '\n') goto yy174;
	goto yy157;
yy177:
	r = p + 1;
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy174;
			goto yy177;
		} else {
			if (yych <= '\r') goto yy176;
			if (yych == ' ') goto yy174;
			goto yy177;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '$') goto yy157;
			if (yych == '/') goto yy173;
			goto yy177;
		} else {
			if (yych <= ':') goto yy174;
			if (yych == '|') goto yy174;
			goto yy177;
		}
	}
yy179:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy177;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy177;
		}
	} else {
		if (yych <= '/') {
			if (yych <= '$') goto yy157;
			if (yych <= '-') goto yy177;
			if (yych >= '/') goto yy157;
		} else {
			if (yych <= ':') {
				if (yych <= '9') goto yy177;
				goto yy157;
			} else {
				if (yych == '|') goto yy157;
				goto yy177;
			}
		}
	}
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy177;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy177;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '$') goto yy157;
			if (yych == '/') goto yy157;
			goto yy177;
		} else {
			if (yych <= ':') goto yy157;
			if (yych == '|') goto yy157;
			goto yy177;
		}
	}
yy181:
	++p;
	yych = *p;
	if (yych <= '#') {
		if (yych <= '\f') {
			if (yych <= 0x00) goto yy157;
			if (yych == '\n') goto yy157;
			goto yy171;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy171;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '$') goto yy157;
			if (yych == '/') goto yy166;
			goto yy171;
		} else {
			if (yych <= ':') goto yy157;
			if (yych == '|') goto yy157;
			goto yy171;
		}
	}
yy182:
	yych = *++p;
	if (yych <= '-') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy157;
			goto yy156;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych == ' ') goto yy157;
			goto yy156;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '.') goto yy183;
			if (yych <= '/') goto yy157;
			goto yy156;
		} else {
			if (yych <= ':') goto yy157;
			if (yych == '|') goto yy157;
			goto yy156;
		}
	}
yy183:
	++p;
	if ((yych = *p) <= ' ') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy157;
			goto yy156;
		} else {
			if (yych <= '\r') goto yy157;
			if (yych <= 0x1F) goto yy156;
			goto yy157;
		}
	} else {
		if (yych <= '9') {
			if (yych == '/') goto yy157;
			goto yy156;
		} else {
			if (yych <= ':') goto yy157;
			if (yych == '|') goto yy157;
			goto yy156;
		}
	}
}

  } while (false);

  return {};
}

bool Lexer::ReadPath(LexedPath* out, std::string* err) {
  const char* p = ofs_;
  const char* q;
  const char* start;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,   0,  32,  32,   0,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 16,  32,  32,  32,   0,  32,  32,  32, 
		 32,  32,  32,  32,  32, 224, 160,  32, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224,   0,  32,  32,  32,  32,  32, 
		 32, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224,  32,  32,  32,  32, 224, 
		 32, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224, 224, 224, 224, 224, 224, 
		224, 224, 224,  32,   0,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
	};
	yych = *p;
	if (yych <= ' ') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy193;
			if (yych >= '\n') goto yy190;
		} else {
			if (yych == '\r') goto yy192;
			if (yych >= ' ') goto yy190;
		}
	} else {
		if (yych <= '9') {
			if (yych == '$') goto yy188;
		} else {
			if (yych <= ':') goto yy190;
			if (yych == '|') goto yy190;
		}
	}
	yyaccept = 0;
	yych = *(q = ++p);
	goto yy205;
yy187:
	{
      continue;
    }
yy188:
	++p;
	if ((yych = *p) <= '-') {
		if (yych <= 0x1F) {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy196;
				goto yy202;
			} else {
				if (yych == '\r') goto yy198;
				goto yy196;
			}
		} else {
			if (yych <= '#') {
				if (yych <= ' ') goto yy199;
				goto yy196;
			} else {
				if (yych <= '$') goto yy199;
				if (yych <= ',') goto yy196;
				goto yy200;
			}
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '9') {
				if (yych <= '/') goto yy196;
				goto yy200;
			} else {
				if (yych <= ':') goto yy199;
				if (yych <= '@') goto yy196;
				goto yy200;
			}
		} else {
			if (yych <= '`') {
				if (yych == '_') goto yy200;
				goto yy196;
			} else {
				if (yych <= 'z') goto yy200;
				if (yych <= '{') goto yy201;
				goto yy196;
			}
		}
	}
yy189:
	{
      last_token_ = start;
      return Error(DescribeLastError(), err);
    }
yy190:
	++p;
yy191:
	{
      p = start;
      break;
    }
yy192:
	yych = *++p;
	if (yych == '\n') goto yy195;
	goto yy189;
yy193:
	++p;
	{
      last_token_ = start;
      return UnexpectedNulError(start, err);
    }
yy195:
	yych = *++p;
	goto yy191;
yy196:
	++p;
yy197:
	{
      last_token_ = start;
      return Error("bad $-escape (literal $ must be written as $$)", err);
    }
yy198:
	yych = *++p;
	if (yych == '\n') goto yy202;
	goto yy197;
yy199:
	yyaccept = 0;
	yych = *(q = ++p);
	goto yy205;
yy200:
	yyaccept = 0;
	yych = *(q = ++p);
	if (yybm[0+yych] & 64) {
		goto yy208;
	}
	goto yy205;
yy201:
	yyaccept = 1;
	yych = *(q = ++p);
	if (yybm[0+yych] & 128) {
		goto yy212;
	}
	goto yy197;
yy202:
	yyaccept = 0;
	q = ++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy204;
	}
	if (yych <= '\r') goto yy187;
	if (yych <= ' ') goto yy202;
	if (yych <= '$') goto yy206;
	goto yy187;
yy204:
	yyaccept = 0;
	q = ++p;
	yych = *p;
yy205:
	if (yybm[0+yych] & 32) {
		goto yy204;
	}
	if (yych <= ' ') goto yy187;
	if (yych >= '%') goto yy187;
yy206:
	++p;
	yych = *p;
	if (yybm[0+yych] & 64) {
		goto yy208;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy202;
		} else {
			if (yych <= '\r') goto yy211;
			if (yych >= ' ') goto yy204;
		}
	} else {
		if (yych <= '/') {
			if (yych == '$') goto yy204;
		} else {
			if (yych <= ':') goto yy204;
			if (yych <= '`') goto yy207;
			if (yych <= '{') goto yy210;
		}
	}
yy207:
	p = q;
	if (yyaccept == 0) {
		goto yy187;
	} else {
		goto yy197;
	}
yy208:
	yyaccept = 0;
	q = ++p;
	yych = *p;
	if (yybm[0+yych] & 64) {
		goto yy208;
	}
	if (yych <= ' ') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy187;
			if (yych <= '\t') goto yy204;
			goto yy187;
		} else {
			if (yych == '\r') goto yy187;
			if (yych <= 0x1F) goto yy204;
			goto yy187;
		}
	} else {
		if (yych <= '/') {
			if (yych == '$') goto yy206;
			goto yy204;
		} else {
			if (yych <= ':') goto yy187;
			if (yych == '|') goto yy187;
			goto yy204;
		}
	}
yy210:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy212;
	}
	goto yy207;
yy211:
	++p;
	yych = *p;
	if (yych == '\n') goto yy202;
	goto yy207;
yy212:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy212;
	}
	if (yych == '}') goto yy204;
	goto yy207;
}

  }
  *out = {};
  out->str_ = StringPiece(ofs_, p - ofs_);
  last_token_ = start;
  ofs_ = p;
  EatWhitespace();
  return true;
}

/// Append the let binding's evaluated value to the output string. The input
/// StringPiece must include a valid binding terminator.
template <typename EvalVar>
static inline void EvaluateBinding(std::string* out_append, StringPiece value,
                                   EvalVar&& eval_var) {
  auto expand = [&eval_var](const char* start, const char* end) {
    StringPiece var(start, end - start);
    eval_var(var);
  };

  const char* p = value.data();
  const char* q;

  for (;;) {
    const char* start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128,   0, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		160, 128, 128, 128,   0, 128, 128, 128, 
		128, 128, 128, 128, 128, 208, 192, 128, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 128, 128, 128, 128, 128, 128, 
		128, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 128, 128, 128, 128, 208, 
		128, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	yych = *p;
	if (yych <= '\f') {
		if (yych <= 0x00) goto yy223;
		if (yych == '\n') goto yy220;
	} else {
		if (yych <= '\r') goto yy222;
		if (yych == '$') goto yy218;
	}
	++p;
	yych = *p;
	goto yy241;
yy217:
	{ out_append->append(start, p - start);   continue; }
yy218:
	yych = *(q = ++p);
	if (yybm[0+yych] & 16) {
		goto yy225;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy230;
		} else {
			if (yych <= '\r') goto yy233;
			if (yych >= ' ') goto yy234;
		}
	} else {
		if (yych <= '/') {
			if (yych == '$') goto yy234;
		} else {
			if (yych <= ':') goto yy234;
			if (yych <= '`') goto yy219;
			if (yych <= '{') goto yy228;
		}
	}
yy219:
	{ assert(false && "bad input in EvaluateBinding"); abort(); }
yy220:
	++p;
yy221:
	{                                         break;    }
yy222:
	yych = *++p;
	if (yych == '\n') goto yy224;
	goto yy219;
yy223:
	yych = *++p;
	goto yy219;
yy224:
	yych = *++p;
	goto yy221;
yy225:
	++p;
	yych = *p;
	if (yybm[0+yych] & 16) {
		goto yy225;
	}
	{ expand(start + 1, p);                   continue; }
yy228:
	yych = *++p;
	if (yych != '}') goto yy237;
yy229:
	p = q;
	goto yy219;
yy230:
	++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy230;
	}
	{                                         continue; }
yy233:
	yych = *++p;
	if (yych == '\n') goto yy230;
	goto yy229;
yy234:
	++p;
	{ out_append->push_back(start[1]);        continue; }
yy236:
	++p;
	yych = *p;
yy237:
	if (yybm[0+yych] & 64) {
		goto yy236;
	}
	if (yych != '}') goto yy229;
	++p;
	{ expand(start + 2, p - 1);               continue; }
yy240:
	++p;
	yych = *p;
yy241:
	if (yybm[0+yych] & 128) {
		goto yy240;
	}
	goto yy217;
}

  }
  assert((p == value.data() + value.size()) &&
         "bad end pos in EvaluateBinding");
}

void EvaluateBindingInScope(std::string* out_append, StringPiece value,
                            ScopePosition pos) {
  EvaluateBinding(out_append, value,
      [out_append, &pos](const HashedStrView& var) {
    Scope::EvaluateVariableAtPos(out_append, var, pos);
  });
}

bool EvaluateBindingOnRule(std::string* out_append, StringPiece value,
                           EdgeEval* edge_eval, std::string* err) {
  bool result = true;
  EvaluateBinding(out_append, value,
      [out_append, edge_eval, &result, err](const HashedStrView& var) {
    result = result && edge_eval->EvaluateVariable(out_append, var, err);
  });
  return result;
}

std::string EvaluateBindingForTesting(StringPiece value) {
  std::string result;
  EvaluateBinding(&result, value, [&result](StringPiece var) {
    result += "[$" + var.AsString() + "]";
  });
  return result;
}

/// Append an evaluated path to the output string.
///
/// This function does not canonicalize the output. Ninja canonicalizes paths for
/// build nodes, but not all paths (e.g. It doesn't canonicalize paths to
/// included ninja files.)
template <typename EvalVar>
static inline void EvaluatePath(std::string* out_append, const LexedPath& path,
                                EvalVar&& eval_var) {
  auto expand = [&eval_var](const char* start, const char* end) {
    StringPiece var(start, end - start);
    eval_var(var);
  };

  const char* p = path.str_.data();
  const char* q;

  for (;;) {
    const char* start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128,   0, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		 32, 128, 128, 128,   0, 128, 128, 128, 
		128, 128, 128, 128, 128, 208, 192, 128, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208,   0, 128, 128, 128, 128, 128, 
		128, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 128, 128, 128, 128, 208, 
		128, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 128,   0, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	yych = *p;
	if (yych <= ' ') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy251;
			if (yych >= '\n') goto yy248;
		} else {
			if (yych == '\r') goto yy250;
			if (yych >= ' ') goto yy248;
		}
	} else {
		if (yych <= '9') {
			if (yych == '$') goto yy246;
		} else {
			if (yych <= ':') goto yy248;
			if (yych == '|') goto yy248;
		}
	}
	++p;
	yych = *p;
	goto yy269;
yy245:
	{ out_append->append(start, p - start);   continue; }
yy246:
	yych = *(q = ++p);
	if (yybm[0+yych] & 16) {
		goto yy253;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy258;
		} else {
			if (yych <= '\r') goto yy261;
			if (yych >= ' ') goto yy262;
		}
	} else {
		if (yych <= '/') {
			if (yych == '$') goto yy262;
		} else {
			if (yych <= ':') goto yy262;
			if (yych <= '`') goto yy247;
			if (yych <= '{') goto yy256;
		}
	}
yy247:
	{ assert(false && "bad input in EvaluatePath"); abort(); }
yy248:
	++p;
yy249:
	{ p = start;                              break;    }
yy250:
	yych = *++p;
	if (yych == '\n') goto yy252;
	goto yy247;
yy251:
	yych = *++p;
	goto yy247;
yy252:
	yych = *++p;
	goto yy249;
yy253:
	++p;
	yych = *p;
	if (yybm[0+yych] & 16) {
		goto yy253;
	}
	{ expand(start + 1, p);                   continue; }
yy256:
	yych = *++p;
	if (yych != '}') goto yy265;
yy257:
	p = q;
	goto yy247;
yy258:
	++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy258;
	}
	{                                         continue; }
yy261:
	yych = *++p;
	if (yych == '\n') goto yy258;
	goto yy257;
yy262:
	++p;
	{ out_append->push_back(start[1]);        continue; }
yy264:
	++p;
	yych = *p;
yy265:
	if (yybm[0+yych] & 64) {
		goto yy264;
	}
	if (yych != '}') goto yy257;
	++p;
	{ expand(start + 2, p - 1);               continue; }
yy268:
	++p;
	yych = *p;
yy269:
	if (yybm[0+yych] & 128) {
		goto yy268;
	}
	goto yy245;
}

  }
  assert((p == path.str_.data() + path.str_.size()) &&
         "bad end pos in EvaluatePath");
}

void EvaluatePathInScope(std::string* out_append, const LexedPath& path,
                         ScopePosition pos) {
  EvaluatePath(out_append, path, [out_append, &pos](const HashedStrView& var) {
    Scope::EvaluateVariableAtPos(out_append, var, pos);
  });
}

void EvaluatePathOnEdge(std::string* out_append, const LexedPath& path,
                        const Edge& edge) {
  EvaluatePath(out_append, path, [out_append, &edge](const HashedStrView& var) {
    // First look for a binding on the edge itself, then fall back to the
    // edge's enclosing scope.
    if (edge.EvaluateVariableSelfOnly(out_append, var))
      return;
    Scope::EvaluateVariableAtPos(out_append, var, edge.pos_.scope_pos());
  });
}

std::string EvaluatePathForTesting(const LexedPath& path) {
  std::string result;
  EvaluatePath(&result, path, [&result](StringPiece var) {
    result += "[$" + var.AsString() + "]";
  });
  return result;
}
